[Feat] 오류 전역 처리 기능
ewoo14/CodeBloom pull request #5
Opened 2024-11-07 06:49 UTC by muncool39

## Summary

- closed #4 

오류 상황을 전역 처리하기 위한 기능을 개발했습니다.

## Key Changes

- 커스텀 익셉션 추가
- 오류 상황을 정의하기 위한 ErrorCode 추가
- 오류 상황 처리를 관리할 RestControllerAdvice 클래스 추가

## Testing

- 테스트를 위해 입력한 코드
```Java
@GetMapping("/")
public String hello(@RequestParam String name) {
    return "hello";
}
```
- 파라미터를 입력하지 않았을 시 오류가 반환 되는 것을 확인할 수 있습니다.
![image](https://github.com/user-attachments/assets/a2363884-0c13-4ddf-a54e-e7c28f618771)

## To Reviewers

- 다른 오류 핸들러에서는 @ResponseStatus를 사용해 반환되는 HttpStatus를 지정했는데, 
커스텀 Exception 의 경우 반환되는 상태가 상황마다 다르기 때문에 ResponseEntity를 사용했습니다. 통일시키는 것이 좋을까요?
- 커스텀 Exception 명을 일단 저희 팀명으로 정했는데, 혹시 다른 의견 있으시면 의견 주시면 감사하겠습니다! 
- 그 외 궁금한 점, 개선할 점 등 편하게 의견 주세요 ! 😃

2024-11-07 06:57 UTC, ewoo14 approved these changes
승인

2024-11-07 07:44 UTC, CLovesJava approved these changes
[GlobalControllerAdvice.java]에 질문 남겨놨습니다.
이대로 하면 될 것 같습니다. 나중에 예외 처리 필요하다고 생각할 때마다 수정하면서 진행하면 문제 없을 것 같습니다.

2024-11-07 07:44 UTC, CLovesJava commented on src/main/java/com/sparta/project/exception/GlobalControllerAdvice.java
- DB에 없는 아이디값 같은 거 나타낼 때는 IllegalArgumentException 대신 CodeBloomException으로 보내주는 건가요?
- 맨 밑에
```
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
@ExceptionHandler(Exception.class)
public ExceptionResponse methodArgumentNotValidException(final Exception e){
    log.error(String.format(ERROR_LOG, e.getParameter(), e.getMessage()));
    return new ExceptionResponse("예기치 못한 오류가 발생했습니다.");
}
```
같은 거 둬서 전체 오류 전부 잡아내는 건 어떤가요? 그러면 오히려 헷갈릴까요

2024-11-07 10:39 UTC, Griotold commented on src/main/java/com/sparta/project/exception/GlobalControllerAdvice.java
맨밑에 Exception.class로 두는 거 찬성입니다. 
하지만, 해당 핸들러에 잡히는 경우, 우리가 예상하지 못한 예외니까 
곧바로 해당 예외를 잡는 핸들러를 추가하는 방식으로 가면 좋을 듯 합니다.

2024-11-07 10:44 UTC, Griotold requested changes
.

2024-11-07 10:44 UTC, Griotold commented on src/main/java/com/sparta/project/exception/GlobalControllerAdvice.java
추가적으로, 좀 더 단단한 예외 처리를 위해 아래에 사항을 추가하면 어떨까요?
예전에 제가 했던 프로젝트에 지정했던 예외 처리입니다.

```

   // url 을 잘못 입력했을 때
    @ExceptionHandler(NoResourceFoundException.class)
    public ResponseEntity<ErrorResponse> handleNoResourceFoundException(NoResourceFoundException e) {
        log.error("NoResourceFound Exception occurred. message={}, className={}", e.getMessage(), e.getClass().getName());
        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(new ErrorResponse(ErrorType.NO_RESOURCE.getDescription(), ErrorType.NO_RESOURCE));
    }

   
    // 쿼리 스트링을 넣어야 하는데 안 넣었을 때
    @ExceptionHandler(MissingServletRequestParameterException.class)
    public ResponseEntity<ErrorResponse> handleMissingServletRequestParameterException(MissingServletRequestParameterException e) {
        log.error("MissingServletRequestParameter Exception occurred. parameterName={}, message={}", e.getParameterName(), e.getMessage());
        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(new ErrorResponse(ErrorType.INVALID_PARAMETER.getDescription(), ErrorType.INVALID_PARAMETER));
    }

    // 쿼리 스트링을 입력 하긴했는데 이상하게 입력했을 때, ex) date=2024-09-25wewfwf
    @ExceptionHandler(MethodArgumentTypeMismatchException.class)
    public ResponseEntity<ErrorResponse> handleMethodArgumentTypeMismatchException(MethodArgumentTypeMismatchException e) {
        log.error("MethodArgumentTypeMismatch Exception occurred. message={}", e.getMessage());
        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(new ErrorResponse(ErrorType.INVALID_PARAMETER.getDescription(), ErrorType.INVALID_PARAMETER));
    }

    @ExceptionHandler(BindException.class)
    public ResponseEntity<ErrorResponse> handleBindException(BindException e) {
        log.error("Bind Exception occurred. message={}, className={}", e.getMessage(), e.getClass().getName());
        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(new ErrorResponse(createMessage(e), ErrorType.INVALID_PARAMETER));
    }

    private String createMessage(BindException e) {
        if (e.getFieldError() != null && e.getFieldError().getDefaultMessage() != null) {
            return e.getFieldError().getDefaultMessage();
        }

        return e.getFieldErrors().stream()
                .map(FieldError::getField)
                .collect(Collectors.joining(", ")) + " 값들이 정확하지 않습니다.";
    }`

2024-11-07 12:28 UTC, ewoo14 commented
에러 처리를 많이 하면 개발하는데 도움은 되지만 오히려 또 다른 에러를 만들 수도 있을 것 같아서 보통 저는 "예기치 못한 에러"라고만 표시하는데, 조금 그런가요?

2024-11-07 16:23 UTC, muncool39 commented on src/main/java/com/sparta/project/exception/GlobalControllerAdvice.java
> DB에 없는 아이디값 같은 거 나타낼 때는 IllegalArgumentException 대신 CodeBloomException으로 보내주는 건가요?

네! 보통 ErrorCode 에 status와 메세지를 정의해서 서비스 층에서 유효성 검사 후 해당 ErrorCode와 함께 CodeBloomException 을 보내는 방식으로 생각하고 있습니다

2024-11-07 16:29 UTC, muncool39 commented
> 에러 처리를 많이 하면 개발하는데 도움은 되지만 오히려 또 다른 에러를 만들 수도 있을 것 같아서 보통 저는 "예기치 못한 에러"라고만 표시하는데, 조금 그런가요?

정말로 서버에서 예기치 못한 오류일 경우는 그렇게 보내야겠지만 모든 오류 상황에 동일하게 메세지를 보낼 경우에 어느 부분이 잘못되었는지 파악하기 어려워 실제로 오류가 발생한 경우 해당 오류를 해결하는 데에 시간이 많이 걸릴 수 있다고 생각합니다! 프론트 입장에서도 그렇지만 백엔드 입장에서도 어느 부분에서 오류가 발생했는지 정확히 알면 개발에 도움이 된다고 생각해요! 😃

2024-11-07 16:45 UTC, muncool39 commented on src/main/java/com/sparta/project/exception/GlobalControllerAdvice.java
> 추가적으로, 좀 더 단단한 예외 처리를 위해 아래에 사항을 추가하면 어떨까요?

참고해서 추가하도록 하겠습니다! 의견 감사합니다! 😃

2024-11-08 06:55 UTC, Griotold commented
확인했습니다.

2024-11-08 06:59 UTC, merged