[Feat] : 도메인별 컨트롤러 초안 작성
ewoo14/CodeBloom pull request #6
Opened 2024-11-07 06:56 UTC by ewoo14

## Summary
도메인별 controller 초안 작성

## Key Changes
각 도메인별 Controller의 초안을 작성하였습니다.

## Testing
아직 dto와 service는 없어 오류가 발생할 수 있습니다.

## To Reviewers
controller 초안이기 때문에 추후 Dto에 따라 변경될 수 있습니다.
예상 dto를 가정하고 작성한 초안입니다.

2024-11-07 07:52 UTC, CLovesJava approved these changes
DTO명이랑 Service 메소드명까지 미리 만들어주셔서 감사합니다. GET POST PATCH DELETE 순서도 좋습니다.

2024-11-07 10:50 UTC, Griotold requested changes
1. @Autowired 대신에 @RequiredArgsConstructor 로 가면 좋을 것 같습니다.
2. 반환값을 공통 DTO로 가는 게 좋을 듯 한데, 팀원들 생각이 궁금합니다.
3. 만약 반환값을 공통 DTO로 안가더라도 ResponseEntity 객체로 감싸야 HttpStatus 상태코드를 서버에서 컨트롤할 수 있을 것 같습니다.

2024-11-07 12:02 UTC, CLovesJava commented
저도 해성님 의견에 동의합니다. 반환값으로 공통 DTO나 ResponseEntity<DTO>는 필요해보입니다.

2024-11-07 12:12 UTC, ewoo14 commented
우선 API 명세서 상 반환값이 다른 경우가 많아서 그렇게 작성하긴 했는데 공통 DTO로 가신다면 명세서부터 수정을 해야할 것 같아요.

2024-11-07 12:20 UTC, ewoo14 commented
우선 말씀하신대로 @Autuwired -> @RequiredArgsConstructor로 변경했습니다.

2024-11-07 16:19 UTC, muncool39 reviewed
메서드와 경로를 잘 작성해 주신 것 같아요! 수고하셨습니다! 👍

한 가지 생각나는 점은 저희가 기능을 개발하고 테스트하려면 결국 프로젝트가 실행이 되어야 하는데, 해당 초안을 그대로 가져올 경우 오류가 발생해 테스트가 어려울 수 있다고 생각합니다!

결론은 일단 `@PathVariable` 이외의 매개변수를 삭제하고 응답을 void 로 설정해 오류가 발생할 수 있는 dto나 service 부분은 삭제하는 것은 어떨까요? 틀은 잡되 오류가 발생하지 않도록 수정하면 좋을 것 같다는 생각이 들었습니다!

2024-11-07 16:23 UTC, ewoo14 commented
아니면 오류 방지를 위한 임의로 dto와 service도 틀만 만들어두는 방법도 있습니다.

2024-11-07 16:37 UTC, muncool39 commented
> 아니면 오류 방지를 위한 임의로 dto와 service도 틀만 만들어두는 방법도 있습니다.

dto는 공통 Response dto를 만든다고 해도 service  클래스는 임의로 만들어도 그 안에 또 메서드를 생성해야 되기 때문에 지금 다 작성하시기에 힘드실거라는 생각이 듭니다! 또 해당 pr 내용이 "컨트롤러 초안 작성" 이기 때문에 service 계층까지 설정한 내용은 포함시키지 않는 편이 좋다고 생각이 들었어요! 틀을 잘 만들어주셨기 때문에 서비스 부분은 추후 해당 도메인 개발 담당자가 만들어도 좋을 것 같아요! 😃
아니면 작성해주신 컨트롤러 클래스들을 인터페이스로 만드는 방법도 있을 것 같습니다! 실제 도메인별 구현할 때 인터페이스를 실제로 구현하도록 해도 될 것 같네요

2024-11-08 13:03 UTC, muncool39 reviewed
전체적으로 틀을 잘 잡아주신 것 같아요 👍 감사합니다! 
상세 조회의 파라미터 관련해서 한 가지 의견 남겼습니다! 그 외에는 실제 구현하면서 조정하면 될 것 같네요 😃

2024-11-08 13:03 UTC, muncool39 commented on src/main/java/com/sparta/project/controller/StoreRequestController.java
> +//            @RequestParam("sortBy") String sortBy) {
상세 조회의 결과는 페이지가 아니여야 하기 때문에 페이지 관련 파라미터는 제거해도 좋을 것 같습니다!
밑의 다른 상세 조회도 마찬가지로 수정하면 될 것 같아요! 😃

2024-11-08 13:16 UTC, ewoo14 commented on src/main/java/com/sparta/project/controller/StoreRequestController.java
> +//            @RequestParam("sortBy") String sortBy) {
StoreRequestController만 해당되는 것인가요? 아니면 다른 Controller들의 상세 조회도 모두 페이지 파라미터는 삭제할까요?

2024-11-08 13:59 UTC, muncool39 commented on src/main/java/com/sparta/project/controller/StoreRequestController.java
> +//            @RequestParam("sortBy") String sortBy) {
해당 컨트롤러가 아니더라도 응답값이 페이지가 아닌 api에 해당 파라미터들이 있다면 수정하시면 좋을 것 같습니다!

2024-11-09 02:16 UTC, Griotold commented
확인했습니다. 고생하셨습니다.

2024-11-09 02:20 UTC, ewoo14 commented
상세 조회 부분은 기존 PathVariable로 하다가 갑자기 QueryParam으로 바꾸느라 그런 부분까지는 생각을 못했네요.
말씀하신 내용은 수정 반영하였습니다.

2024-11-09 02:26 UTC, ewoo14 commented
@muncool39 님께서 approval 하신다면 머지 진행하겠습니다.

2024-11-09 05:48 UTC, muncool39 approved these changes
확인했습니다!👍 수고하셨습니다~

2024-11-09 06:37 UTC, merged