[Feat] entity 생성
ewoo14/CodeBloom pull request #7
Opened 2024-11-07 07:04 UTC by CLovesJava

## Summary

- closed #
Entity 설계했습니다.

## Key Changes
- Entity 설계했습니다.
- gradle에 JPA 추가 했습니다.

## Testing
부팅 시 DB에 Entity 설정대로 table 만들어졌습니다.

## To Reviewers
- 아직 피드백 받기 전이라 수정할 여지가 있어서 빠르게 만드는 데에만 집중했습니다.
- enum 보시면 일단 기본 상수만 적어놨습니다. 나중에 enum 사용하실 때 추가하고 싶은 사항 있으시면 하시거나 의논하면 될 것 같습니다.
- nullable=true 같은 경우에는 제가 임의로 필요하다고 생각되는 곳에 넣었습니다. 도메인 설계하시면서 NOT NULL 풀고 싶다고 생각되시면 빼면 될 것 같습니다.
- createEntity 정적 메소드나 update용 메소드 또한 도메인 개발하면서 직접 쓰시면 됩니다.
- FK는 @ManyToOne 단방향 매핑으로만 설계했습니다. 양방향 매핑이나 OneToOne 필요하시면 수정하시면 됩니다.

2024-11-07 11:13 UTC, Griotold commented on src/main/java/com/sparta/project/domain/Store.java
> +	@ManyToOne(fetch = FetchType.LAZY)
@OnDelete 어노테이션에 대해서 의문이 듭니다.
Owner가 삭제되면 Store가 사라져야하나?
category가 Store가 삭제되어야 하나?
Location이 삭제되면 Store가 삭제되어야 하나?
하는 고민이 생기네요.

2024-11-07 11:16 UTC, Griotold commented on src/main/java/com/sparta/project/domain/enums/OrderType.java
> +package com.sparta.project.domain.enums;
보통 enum을 만들 때 description 필드를 넣어서 "온라인", "오프라인", "카드", "현금".. 등등 주석의 역할을 description이 하게끔 합니다. 현재로서는 모든 enum 타입이 명확해서 필요없긴 한 거 같은데 팀원들 의견이 궁금합니다.

2024-11-07 11:22 UTC, Griotold commented on src/main/java/com/sparta/project/domain/Order.java
> +
Order를 조회할 때 OrderFood 들도 조회를 해야 해서 일대다 매핑이 필요해 보입니다.
그렇게 되면 @ToString이 양쪽에 걸려있으면 stackOverFlow가 날 수도 있을 것 같습니다.

2024-11-07 11:26 UTC, Griotold requested changes
1. Order 조회시 OrderFood 일대다 매핑이 필요할 것 같다는 생각입니다.
- 이 경우 @ToString을 주의해서 사용해야 합니다.

2. @OnDelete 어노테이션의 경우, Store 엔티티에서 
- owner가 삭제되면 Store도 같이 삭제되어야 하는가?
- category가 삭제되면 store도 같이 삭제되어야 하는가?
- location이 삭제되면 store도 같이 삭제되어야 하는가?
고민이 생깁니다.

3. enum에 description 필드를 넣는 걸 선호하는데 팀원 분들의 의견이 궁금합니다.

2024-11-07 11:50 UTC, CLovesJava commented on src/main/java/com/sparta/project/domain/Order.java
> +
Order에 일대다 매핑 추가하고  OrderFood에 ToString 삭제하겠습니다.

2024-11-07 11:59 UTC, CLovesJava commented on src/main/java/com/sparta/project/domain/Store.java
> +	@ManyToOne(fetch = FetchType.LAZY)
급하게 만드느라 신경을 못 썼네요. 해당 부분은 저도 동의합니다. 물리적으로는 실제로 삭제될 일이 없긴 하지만, 만약을 위해서라도 SET DEFAULT나 SET NULL은 적용해야 할 것 같은데 어떻게 생각하시나요?

2024-11-07 16:05 UTC, muncool39 reviewed
확인했습니다! 의견 남겼습니다! 😃

2024-11-07 16:05 UTC, muncool39 commented on src/main/java/com/sparta/project/domain/Address.java
> +@Table(name="p_address")
엔티티 설정 관련해서 클래스 단위가 아닌 생성자 메서드에 빌더패턴을 적용하는 방법을 사용하는건 어떨까요?
참고가 될만한 사이트입니다!
- https://velog.io/@mooh2jj/%EC%98%AC%EB%B0%94%EB%A5%B8-%EC%97%94%ED%8B%B0%ED%8B%B0-Builder-%EC%82%AC%EC%9A%A9%EB%B2%95

해당 글 읽어보시고 괜찮으시면 변경해보면 좋을 것 같아요! 😃

2024-11-07 16:05 UTC, muncool39 commented on src/main/java/com/sparta/project/domain/BaseEntity.java
> +public class BaseEntity {
부모 클래스로만 사용되기 때문에 abstract를 붙여 추상 클래스로 변경해 사용하면 좋을 것 같습니다!

2024-11-07 16:05 UTC, muncool39 commented on src/main/java/com/sparta/project/domain/BaseEntity.java
> +    private LocalDateTime deletedBy;
createBy 처럼 나머지 _by 필드도 String 타입으로 변경해야 될 것 같습니다!

2024-11-07 16:05 UTC, muncool39 commented on src/main/java/com/sparta/project/domain/enums/OrderType.java
> +package com.sparta.project.domain.enums;
저도 설명이 있으면 의미 파악에 도움이 된다고 생각해서 적용해도 좋을 것 같습니다!

2024-11-07 16:05 UTC, muncool39 commented on build.gradle
> +	implementation 'org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4.1:1.16'
혹시 해당 의존성은 어느 곳에 사용하기 위해 추가하신 건지 알 수 있을까요?
엔티티 생성 내용과 무관하다면 제거해도 좋을 것 같습니다!

2024-11-07 16:16 UTC, CLovesJava commented on src/main/java/com/sparta/project/domain/BaseEntity.java
> +    private LocalDateTime deletedBy;
앗 미처 확인 못했네요 감사합니다

2024-11-07 17:33 UTC, CLovesJava commented on src/main/java/com/sparta/project/domain/enums/OrderType.java
> +package com.sparta.project.domain.enums;
description 적용 완료했습니다!

2024-11-07 17:33 UTC, CLovesJava commented on src/main/java/com/sparta/project/domain/Address.java
> +@Table(name="p_address")
저도 오늘 막 찾아본 글이었는데 신기하네요 ㅋㅋㅋ 저도 바꾸면 좋다고 생각해서 적용했습니다.

2024-11-07 17:37 UTC, CLovesJava commented
요청하신 사항 전부 저도 동의하는 부분이라 모두 반영했습니다!
- 생성자 Builder에서 default 들어가는 값은 파라미터에서 제외했습니다.
- BaseEntity는 스프링 시큐리티 부분이 구현되면 AuditorAware 구현체를 사용하는 방법으로 구현하겠습니다. 다음 사이트에서 참고 가능합니다. https://javacpro.tistory.com/85
- 위 사항들은 코드에도 주석으로 적어놨습니다.

2024-11-08 05:29 UTC, CLovesJava commented
피드백 사항, 테이블명 바뀐 사항 전부 반영했습니다.
- 바뀐 사항이 많다보니 commit이 많습니다. 개별로 보고 싶으시면 commit 기록 확인하시면 됩니다.
- ``@OnDelete`` 설정 관련해서는 튜터님께 여쭤본 결과 DB는 인프라기 때문에 개발 환경과 독립적으로 봐야 한다고 하셔서 삭제했습니다.
- 논리적인 삭제 전파는 Entity 함수 내에서 delete() 안에 하위 Entity의 delete()를 호출하는 방식을 추천하셨습니다. 그런데 그 방식을 사용하기 위해서는 @OneToMany를 추가해줘야 합니다. 그래서 구현 시에 필요하시다면 @OneToMany로 매핑을 하시면 될 것 같습니다.

2024-11-08 07:22 UTC, merged